# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='effective_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conf',
            name='effective_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='effective_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dept_supervisor',
            name='effective_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='effective_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job_data',
            name='effective_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='org_relation',
            name='effective_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='effective_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='probation_data',
            name='effective_flag',
            field=models.IntegerField(default=0),
        ),
    ]
